name: Generate
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-generate-action@v1
        with:
          input: proto
